/* Generated by famco/build.mjs from famco/agency.js. Edit that file and rebuild, not this one. */
/* ==========================================================
   FamCo Properties — details shared by every house site.
   build.mjs copies this file into each house folder, so edit
   it HERE, then run:  node famco/build.mjs
   ========================================================== */

window.AGENCY = {

  // Keep this false until FamCo Properties is registered with HMRC for
  // anti-money-laundering supervision and has joined a property redress
  // scheme. Trading as an estate agency before HMRC registration is a
  // criminal offence. While false, every house site shows as a private
  // sale by the owner and none of the FamCo details below appear.
  live: false,

  name: "FamCo Properties",
  url: "",                 // FamCo Properties' own website, once there is one

  // One or two sentences shown next to the enquiry form on every house.
  blurb: "Every FamCo home has its own website, film and social campaign, and every viewing and question goes straight to the FamCo team.",

  phone: "",               // shown next to the enquiry form when filled in
  email: "",

  // Where enquiries go for every house (unless a house sets its own).
  // Sign up at formspree.io and paste the form ID (the bit after /f/).
  enquiries: {
    formspreeId: "",
    fallbackEmail: "",
  },

  // Shown in every footer once filled in.
  redress: "",             // e.g. "Member of The Property Ombudsman (membership no. ...)"
  company: {               // UK company websites must show these
    legalName: "",         // e.g. "FamCo Properties Ltd"
    number: "",            // Companies House number
    registeredOffice: "",  // registered office address
  },

  // Options for "How did you hear about it?" on every enquiry form.
  heardVia: [
    "Facebook",
    "Instagram",
    "Google search",
    "FamCo Properties website",
    "Friend or family",
    "Walking or driving past",
    "Other",
  ],

  // Footer small print on every house while FamCo is live.
  disclaimer: "These particulars are a general guide only and don't form part of any offer or contract. Measurements are approximate, and no services or appliances have been tested. Please check anything that matters to you before committing.",
};
